<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="zd2.css" ?>

<!DOCTYPE list[
<!ELEMENT list (head,nsong,ndata,read,song,data)>
<!ELEMENT head (ntitle,nbook)>
<!ELEMENT read (title,book)>
<!ELEMENT nsong (#PCDATA)>
<!ELEMENT ndata (#PCDATA)>
<!ELEMENT song (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ENTITY like "я люблю эту песню">
<!ENTITY good "это хорошая песня">
]>

<list>

<head>
    <nsong>Песня</nsong>
    <ndata>Дата</ndata>
</head>

<read>
    <song>Destination Freestyle &like;</song>
    <data>12.12.2022</data>
</read>

<read>
    <song>Give Me A Kiss</song>
    <data>11.11.2022</data>
</read>

<read>
    <song>Caroline &good;</song>
    <data>10.10.2022</data>
</read>
</list>